name: modern_robotics
description: Dart implementation of [Modern Robotics book
  code](https://github.com/NxRLab/ModernRobotics)
version: 0.1.0+dev
repository: https://github.com/Abdulrasheed1729/modern_robotics.dart
environment:
  sdk: ^3.1.1

# Add regular dependencies here.
dependencies:
  scidart: ^0.0.2-dev.12
# path: ^1.8.0
dev_dependencies:
  coverage: ^1.6.3
  test: ^1.21.0
  very_good_analysis: ^5.1.0
